### ISSUE TITLE
Deploy Script Broken

### ISSUE THREAD

**Issue by Firerouge** [wsu-lug/lug-site#20]
@andrewbates09 Correct me if I'm wrong, but I thought, lug.wsu.edu was supposed to use webhooks to deploy any updates to the master branch.

Seems like that may not be happening. The deploy key in the repo is saying last used in the last 5 months. Commit 4ac38e6873f38458c0d0c1cb85a460c9386a0b5c is not reflected on https://lug.wsu.edu/office.html

**Comment by andrewbates09** [comment]
@Firerouge @czhanacek - it looks like things are broken due to [Codeship App Migration](https://blog.codeship.com/updated-github-integration/), so I'm looking into migrating the projects that aren't truly building anymore.

Also, no not webhooks, it uses Codeship (as seen in the readme of the repo) for deployment.  Codeship is simply rsync'ing content to the appropriate LUG server(s).

**Comment by andrewbates09** [comment]
NVM, looks to be good and live - 6e1d27c

**Comment by czhanacek** [comment]
Looks like commit 4ac38e6 is now reflected on the site
